import { readdir, readFile } from "fs/promises";
import { join, basename } from "path";

/**
 * COS API layer -- Phase 1 reads directly from the filesystem.
 * Phase 2+ will call the COS MCP server via subprocess or HTTP.
 */

const COS_ROOT = process.env.COS_ROOT || join(process.cwd(), "..");

// ---------------------------------------------------------------------------
// Status
// ---------------------------------------------------------------------------

export interface CosStatus {
  projectName: string;
  phase: string;
  cosVersion: string;
  rulesCount: number;
  hooksCount: number;
  skillsCount: number;
  packagesCount: number;
  activeSessions: number;
}

export async function getCosStatus(): Promise<CosStatus> {
  const [rulesCount, hooksCount, skillsCount, packagesCount, config] =
    await Promise.all([
      countFiles(join(COS_ROOT, "rules"), ".md"),
      countFiles(join(COS_ROOT, "hooks"), ".sh"),
      countSkills(join(COS_ROOT, "skills")),
      countDirectories(join(COS_ROOT, "packages")),
      readCosConfig(),
    ]);

  return {
    projectName: config.projectName,
    phase: config.phase,
    cosVersion: config.version,
    rulesCount,
    hooksCount,
    skillsCount,
    packagesCount,
    activeSessions: 0,
  };
}

// ---------------------------------------------------------------------------
// Rules
// ---------------------------------------------------------------------------

export interface CosRule {
  name: string;
  path: string;
}

export async function getRules(): Promise<CosRule[]> {
  const rulesDir = join(COS_ROOT, "rules");
  const rules: CosRule[] = [];

  try {
    const entries = await readdir(rulesDir);
    for (const entry of entries) {
      if (entry.endsWith(".md")) {
        const name = basename(entry, ".md");
        rules.push({ name, path: `rules/${entry}` });
      }
    }
  } catch {
    // Directory may not exist in test environments
  }

  return rules.sort((a, b) => a.name.localeCompare(b.name));
}

// ---------------------------------------------------------------------------
// Skills
// ---------------------------------------------------------------------------

export interface CosSkill {
  name: string;
  description: string;
  trigger?: string;
  autoGenerated: boolean;
}

export async function getSkills(): Promise<CosSkill[]> {
  const skillsDir = join(COS_ROOT, "skills");
  const skills: CosSkill[] = [];

  try {
    const entries = await readdir(skillsDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;

      const skillPath = join(skillsDir, entry.name, "SKILL.md");
      try {
        const content = await readFile(skillPath, "utf-8");
        const description = extractFirstParagraph(content);
        const trigger = entry.name;
        const autoGenerated = entry.name.startsWith("auto-") ||
          content.includes("auto-generated: true");

        skills.push({
          name: entry.name,
          description,
          trigger,
          autoGenerated,
        });
      } catch {
        // SKILL.md may not exist for all directories
        skills.push({
          name: entry.name,
          description: "No description available",
          autoGenerated: false,
        });
      }
    }
  } catch {
    // Directory may not exist
  }

  return skills.sort((a, b) => a.name.localeCompare(b.name));
}


// ---------------------------------------------------------------------------
// Primitive Surface Coverage
// ---------------------------------------------------------------------------

export interface PrimitiveSurfaceCoverageSummary {
  totalPrimitives: number;
  gaps: number;
  unclassifiedGaps: number;
  surfacesByKind: Record<string, number>;
  surfaceProjectedOrWired: Record<string, number>;
  consumesReport: boolean;
  mode: "observe-only";
}

export interface VcsActionReceiptSummary {
  total: number;
  byTrust: Record<string, number>;
  byEventType: Record<string, number>;
  bySource: Record<string, number>;
  consumesReport: boolean;
  mode: "observe-only";
}

export interface TuiActionReceiptSummary {
  total: number;
  byAction: Record<string, number>;
  byOutcome: Record<string, number>;
  consumesReport: boolean;
  mode: "observe-only";
}

export async function getPrimitiveSurfaceCoverageSummary(): Promise<PrimitiveSurfaceCoverageSummary> {
  const reportPath = join(COS_ROOT, "docs", "reports", "primitive-harness-coverage-latest.json");

  try {
    const content = await readFile(reportPath, "utf-8");
    const report = JSON.parse(content);
    const summary = report.summary || {};

    return {
      totalPrimitives: Number(summary.total_primitives || 0),
      gaps: Number(summary.gaps || 0),
      unclassifiedGaps: Number(summary.unclassified_gaps || 0),
      surfacesByKind: summary.surfaces_by_kind || {},
      surfaceProjectedOrWired: summary.surface_projected_or_wired || summary.harness_projected_or_wired || {},
      consumesReport: true,
      mode: "observe-only",
    };
  } catch {
    return {
      totalPrimitives: 0,
      gaps: 0,
      unclassifiedGaps: 0,
      surfacesByKind: {},
      surfaceProjectedOrWired: {},
      consumesReport: false,
      mode: "observe-only",
    };
  }
}


export interface PrimitiveProjectionFidelitySummary {
  contracts: number;
  projectionRows: number;
  aligned: number;
  gaps: number;
  unknown: number;
  pendingRuntimeSmoke: number;
  consumesReport: boolean;
  mode: "observe-only";
}

export interface OpenCodePrimitiveAdapterSmokeSummary {
  status: string;
  version: string;
  supportedPrimitives: number;
  ledgerRows: number;
  consumesReport: boolean;
  mode: "observe-only";
}

export interface PortableAiConsumerSmokeSummary {
  status: string;
  overlayFiles: number;
  primitiveFiles: number;
  registryBacked: number;
  lifecycleDerived: number;
  noCanonicalMutation: boolean;
  consumesReport: boolean;
  mode: "observe-only";
}

export interface PrimitiveServiceHeadlessSmokeSummary {
  status: string;
  ledgerRows: number;
  primitiveCount: number;
  contentFreeRows: boolean;
  consumesReport: boolean;
  mode: "observe-only";
}

export async function getPrimitiveProjectionFidelitySummary(): Promise<PrimitiveProjectionFidelitySummary> {
  const reportPath = join(COS_ROOT, "docs", "reports", "primitive-projection-fidelity-latest.json");
  try {
    const report = JSON.parse(await readFile(reportPath, "utf-8"));
    const summary = report.summary || {};
    return {
      contracts: Number(summary.contracts || 0),
      projectionRows: Number(summary.projection_rows || 0),
      aligned: Number(summary.aligned || 0),
      gaps: Number(summary.gaps || 0),
      unknown: Number(summary.unknown || 0),
      pendingRuntimeSmoke: Number(summary.pending_runtime_smoke || 0),
      consumesReport: true,
      mode: "observe-only",
    };
  } catch {
    return { contracts: 0, projectionRows: 0, aligned: 0, gaps: 0, unknown: 0, pendingRuntimeSmoke: 0, consumesReport: false, mode: "observe-only" };
  }
}

export async function getOpenCodePrimitiveAdapterSmokeSummary(): Promise<OpenCodePrimitiveAdapterSmokeSummary> {
  const reportPath = join(COS_ROOT, "docs", "reports", "opencode-primitive-adapter-smoke-latest.json");
  try {
    const report = JSON.parse(await readFile(reportPath, "utf-8"));
    return {
      status: String(report.status || "unknown"),
      version: String((report.opencode || {}).version || ""),
      supportedPrimitives: Array.isArray(report.supported_primitives) ? report.supported_primitives.length : 0,
      ledgerRows: Number(report.ledger_row_count || 0),
      consumesReport: true,
      mode: "observe-only",
    };
  } catch {
    return { status: "unavailable", version: "", supportedPrimitives: 0, ledgerRows: 0, consumesReport: false, mode: "observe-only" };
  }
}

export async function getPortableAiConsumerSmokeSummary(): Promise<PortableAiConsumerSmokeSummary> {
  const reportPath = join(COS_ROOT, "docs", "reports", "portable-ai-consumer-smoke-latest.json");
  try {
    const report = JSON.parse(await readFile(reportPath, "utf-8"));
    return {
      status: String(report.status || "unknown"),
      overlayFiles: Number(report.overlay_file_count || 0),
      primitiveFiles: Number(report.primitive_file_count || 0),
      registryBacked: Number(report.registry_backed_count || 0),
      lifecycleDerived: Number(report.lifecycle_derived_count || 0),
      noCanonicalMutation: Boolean(report.no_canonical_mutation),
      consumesReport: true,
      mode: "observe-only",
    };
  } catch {
    return { status: "unavailable", overlayFiles: 0, primitiveFiles: 0, registryBacked: 0, lifecycleDerived: 0, noCanonicalMutation: false, consumesReport: false, mode: "observe-only" };
  }
}

export async function getPrimitiveServiceHeadlessSmokeSummary(): Promise<PrimitiveServiceHeadlessSmokeSummary> {
  const reportPath = join(COS_ROOT, "docs", "reports", "primitive-service-headless-smoke-latest.json");
  try {
    const report = JSON.parse(await readFile(reportPath, "utf-8"));
    return {
      status: String(report.status || "unknown"),
      ledgerRows: Number(report.ledger_row_count || 0),
      primitiveCount: Array.isArray(report.primitive_ids) ? report.primitive_ids.length : 0,
      contentFreeRows: Boolean(report.content_free_rows),
      consumesReport: true,
      mode: "observe-only",
    };
  } catch {
    return { status: "unavailable", ledgerRows: 0, primitiveCount: 0, contentFreeRows: false, consumesReport: false, mode: "observe-only" };
  }
}

export async function getVcsActionReceiptSummary(): Promise<VcsActionReceiptSummary> {
  const metricsPath = join(COS_ROOT, ".cognitive-os", "metrics", "vcs-actions.jsonl");
  const empty = {
    total: 0,
    byTrust: {},
    byEventType: {},
    bySource: {},
    consumesReport: false,
    mode: "observe-only" as const,
  };

  try {
    const content = await readFile(metricsPath, "utf-8");
    const byTrust: Record<string, number> = {};
    const byEventType: Record<string, number> = {};
    const bySource: Record<string, number> = {};
    let total = 0;

    for (const line of content.split("\n")) {
      if (!line.trim()) continue;
      try {
        const receipt = JSON.parse(line);
        total += 1;
        const trust = String(receipt.trust || "unknown");
        const eventType = String(receipt.event_type || "unknown");
        const source = String(receipt.source || "unknown");
        byTrust[trust] = (byTrust[trust] || 0) + 1;
        byEventType[eventType] = (byEventType[eventType] || 0) + 1;
        bySource[source] = (bySource[source] || 0) + 1;
      } catch {
        // Ignore malformed telemetry rows; the Python report path does the same.
      }
    }

    return {
      total,
      byTrust,
      byEventType,
      bySource,
      consumesReport: true,
      mode: "observe-only",
    };
  } catch {
    return empty;
  }
}

export async function getTuiActionReceiptSummary(): Promise<TuiActionReceiptSummary> {
  const metricsPath = join(COS_ROOT, ".cognitive-os", "metrics", "tui-actions.jsonl");
  const empty = {
    total: 0,
    byAction: {},
    byOutcome: {},
    consumesReport: false,
    mode: "observe-only" as const,
  };

  try {
    const content = await readFile(metricsPath, "utf-8");
    const byAction: Record<string, number> = {};
    const byOutcome: Record<string, number> = {};
    let total = 0;

    for (const line of content.split("\n")) {
      if (!line.trim()) continue;
      try {
        const receipt = JSON.parse(line);
        if (receipt.schema_version !== "cos-tui-action-receipt.v1") continue;
        total += 1;
        const action = String(receipt.action || "unknown");
        const outcome = String(receipt.outcome || "unknown");
        byAction[action] = (byAction[action] || 0) + 1;
        byOutcome[outcome] = (byOutcome[outcome] || 0) + 1;
      } catch {
        // Ignore malformed telemetry rows; cos-tui --receipts does the same.
      }
    }

    return {
      total,
      byAction,
      byOutcome,
      consumesReport: true,
      mode: "observe-only",
    };
  } catch {
    return empty;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function countFiles(dir: string, ext: string): Promise<number> {
  try {
    const entries = await readdir(dir);
    return entries.filter((e) => e.endsWith(ext)).length;
  } catch {
    return 0;
  }
}

async function countSkills(dir: string): Promise<number> {
  try {
    const entries = await readdir(dir, { withFileTypes: true });
    return entries.filter((e) => e.isDirectory()).length;
  } catch {
    return 0;
  }
}

async function countDirectories(dir: string): Promise<number> {
  try {
    const entries = await readdir(dir, { withFileTypes: true });
    return entries.filter((e) => e.isDirectory()).length;
  } catch {
    return 0;
  }
}

interface CosConfig {
  projectName: string;
  phase: string;
  version: string;
}

async function readCosConfig(): Promise<CosConfig> {
  try {
    const content = await readFile(
      join(COS_ROOT, "cognitive-os.yaml"),
      "utf-8"
    );
    // Simple YAML extraction without a parser dependency
    const phase = extractYamlValue(content, "phase") || "reconstruction";
    const name = extractYamlValue(content, "name") || "luum-agent-os";
    const version = extractYamlValue(content, "version") || "0.0.0";
    return { projectName: name, phase, version };
  } catch {
    return {
      projectName: "unknown",
      phase: "unknown",
      version: "0.0.0",
    };
  }
}

function extractYamlValue(content: string, key: string): string | null {
  const regex = new RegExp(`^\\s*${key}:\\s*(.+)$`, "m");
  const match = content.match(regex);
  return match ? match[1].trim().replace(/^["']|["']$/g, "") : null;
}

function extractFirstParagraph(markdown: string): string {
  const lines = markdown.split("\n");
  const paragraphLines: string[] = [];
  let started = false;

  for (const line of lines) {
    const trimmed = line.trim();
    // Skip frontmatter and headings
    if (trimmed.startsWith("---") || trimmed.startsWith("#")) {
      if (started) break;
      continue;
    }
    if (trimmed === "") {
      if (started) break;
      continue;
    }
    started = true;
    paragraphLines.push(trimmed);
  }

  return paragraphLines.join(" ").slice(0, 200) || "No description";
}
