package pattern

import (
	"bytes"
	"crypto/sha256"
	"database/sql"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"
	"unicode"

	"github.com/luum/cos-dispatch/internal/config"
)

// SQLGenerator implements Generator, emitting Go source stubs to disk and
// recording them in the generated_artifacts table with enabled=0 (ADR-004).
type SQLGenerator struct {
	db        *sql.DB
	outputDir string
	moduleDir string // Go module root; used for `go build` verification
	cfg       config.AutoGenerateConfig
}

// NewSQLGenerator returns a SQLGenerator with outputDir created if absent.
func NewSQLGenerator(db *sql.DB, cfg config.AutoGenerateConfig) (*SQLGenerator, error) {
	return NewSQLGeneratorWithModuleDir(db, cfg, "")
}

// NewSQLGeneratorWithModuleDir is like NewSQLGenerator but accepts an explicit
// module root for the `go vet` compile check.
func NewSQLGeneratorWithModuleDir(db *sql.DB, cfg config.AutoGenerateConfig, moduleDir string) (*SQLGenerator, error) {
	if db == nil {
		return nil, fmt.Errorf("generator: db must not be nil")
	}
	if cfg.OutputDir == "" {
		cfg.OutputDir = "generated/"
	}
	if err := os.MkdirAll(cfg.OutputDir, 0o755); err != nil {
		return nil, fmt.Errorf("generator: create output dir %q: %w", cfg.OutputDir, err)
	}
	if moduleDir == "" {
		moduleDir = "."
	}
	return &SQLGenerator{db: db, outputDir: cfg.OutputDir, moduleDir: moduleDir, cfg: cfg}, nil
}

// patternShortName maps supported pattern types to their short tag.
func patternShortName(t PatternType) (string, bool) {
	switch t {
	case PatternRepeatedFailure:
		return "RepeatFail", true
	case PatternErrorCluster:
		return "Cluster", true
	case PatternMissingCoverage:
		return "MissCov", true
	default:
		return "", false
	}
}

// artifactName derives the struct name (AutoValidator_RepeatFail_a3f8c2d1)
// and file name (auto_validator_repeat_fail_a3f8c2d1.go) for a pattern.
func artifactName(pt PatternType, sourceID int64, suggestion string) (structName, fileName string) {
	short, _ := patternShortName(pt)
	h := sha256.Sum256([]byte(fmt.Sprintf("%s%d%s", pt.String(), sourceID, suggestion)))
	hash := fmt.Sprintf("%x", h[:4])
	structName = fmt.Sprintf("AutoValidator_%s_%s", short, hash)
	fileName = camelToSnake(structName) + ".go"
	return
}

// camelToSnake converts CamelCase (with underscores) to lower_snake_case.
func camelToSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) && i > 0 {
			prev := rune(s[i-1])
			if unicode.IsLower(prev) || prev == '_' {
				b.WriteByte('_')
			}
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

// stubTmpl is the Go source template for all supported pattern types.
// It must produce a compilable file when rendered.
var stubTmpl = template.Must(template.New("stub").Parse(`// Code generated by cos-dispatch. DO NOT EDIT.
// Source pattern: {{.PatternType}} (confidence={{printf "%.2f" .Confidence}})
// Generated: {{.GeneratedAt}}
// This artifact is DISABLED by default.
// Enable via: cos-dispatch review --enable {{.Name}}

package generated

import (
	"context"

	"github.com/luum/cos-dispatch/internal/validator"
	"github.com/luum/cos-dispatch/pkg/hook"
)

// {{.Name}} is an auto-generated validator stub from pattern {{.PatternType}}.
// Pattern suggestion: {{.Suggestion}}
type {{.Name}} struct{}

func (v *{{.Name}}) Name() string { return "{{.KebabName}}" }

func (v *{{.Name}}) Category() validator.ValidatorCategory {
	return validator.CategoryCPU
}

func (v *{{.Name}}) Validate(_ context.Context, _ *hook.Context) *validator.Result {
	// TODO: Implement remediation logic for pattern {{.PatternType}}.
	// Suggestion: {{.Suggestion}}
	return &validator.Result{
		Passed:  true,
		Message: "auto-generated stub — implement logic",
	}
}
`))

type stubData struct {
	Name        string
	KebabName   string
	PatternType string
	Confidence  float64
	Suggestion  string
	GeneratedAt string
}

// configSnippet returns a TOML snippet that registers the artifact as disabled.
func configSnippet(structName, kebabName string) string {
	return fmt.Sprintf(`[[validators]]
name = %q
enabled = false
# generated by cos-dispatch — review with: cos-dispatch review --enable %s
`, kebabName, structName)
}

// Generate filters patterns by confidence and MaxPerSession, emits Go stubs,
// writes files to outputDir, inserts DB rows with enabled=0, and verifies each
// file compiles.  Files/rows that fail compilation are rolled back atomically.
func (g *SQLGenerator) Generate(patterns []DetectedPattern) ([]GeneratedArtifact, error) {
	var results []GeneratedArtifact

	for _, p := range patterns {
		if len(results) >= g.cfg.MaxPerSession {
			break
		}

		if p.Confidence < g.cfg.ConfidenceThreshold {
			continue
		}

		short, supported := patternShortName(p.Type)
		if !supported {
			log.Printf("generator: skipping unsupported pattern type %s", p.Type.String())
			continue
		}
		_ = short // used inside artifactName

			// source_pattern_id is 0: DetectedPattern carries no persisted ID.
		// Phase 5.3 will wire this to the detected_patterns table.
		structName, fileName := artifactName(p.Type, 0, p.Suggestion)
		kebabName := structToKebab(structName)

		data := stubData{
			Name:        structName,
			KebabName:   kebabName,
			PatternType: p.Type.String(),
			Confidence:  p.Confidence,
			Suggestion:  p.Suggestion,
			GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		}

		var buf bytes.Buffer
		if err := stubTmpl.Execute(&buf, data); err != nil {
			// Template failure: log and continue (no file, no DB row).
			log.Printf("generator: template error for %s: %v", structName, err)
			continue
		}
		code := buf.String()

		filePath := filepath.Join(g.outputDir, fileName)
		snippet := configSnippet(structName, kebabName)

		// Write the file.
		if err := os.WriteFile(filePath, []byte(code), 0o644); err != nil {
			log.Printf("generator: write %s: %v", filePath, err)
			continue
		}

		// Verify compilation.  On failure, delete file and skip DB insert.
		if err := verifyCompiles(g.moduleDir, filePath); err != nil {
			log.Printf("generator: compile check failed for %s: %v — rolling back", structName, err)
			_ = os.Remove(filePath)
			continue
		}

		// Insert into DB with enabled=0.
		res, err := g.db.Exec(
			`INSERT INTO generated_artifacts
			 (name, artifact_type, source_pattern_id, language, code, config_snippet, confidence, enabled, feedback)
			 VALUES (?, 'validator', NULL, 'go', ?, ?, ?, 0, '')`,
			structName, code, snippet, p.Confidence,
		)
		if err != nil {
			log.Printf("generator: db insert %s: %v — removing file", structName, err)
			_ = os.Remove(filePath)
			continue
		}
		id, _ := res.LastInsertId()

		results = append(results, GeneratedArtifact{
			Name:            structName,
			ArtifactType:    "validator",
			SourcePatternID: id,
			Language:        "go",
			Code:            code,
			ConfigSnippet:   snippet,
			Confidence:      p.Confidence,
			Enabled:         false,
			Feedback:        "",
		})
	}

	return results, nil
}

// verifyCompiles checks that the given Go source file compiles cleanly.
// It runs `go vet` from moduleDir on the package containing filePath.
// filePath must be inside moduleDir for the module resolver to find imports.
func verifyCompiles(moduleDir, filePath string) error {
	rel, err := filepath.Rel(moduleDir, filePath)
	if err != nil {
		return fmt.Errorf("verifyCompiles: cannot relativize %s from %s: %w", filePath, moduleDir, err)
	}
	// Get the directory portion as a package pattern.
	pkgDir := "./" + filepath.ToSlash(filepath.Dir(rel))
	cmd := exec.Command("go", "vet", pkgDir)
	cmd.Dir = moduleDir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// ApplyFeedback updates the DB row; on FeedbackDeleted also removes the file.
// The row is kept as an audit record (ADR-004).
func (g *SQLGenerator) ApplyFeedback(artifactName string, decision FeedbackDecision) error {
	enabled := 0
	if decision == FeedbackEnabled {
		enabled = 1
	}

	res, err := g.db.Exec(
		`UPDATE generated_artifacts SET feedback = ?, enabled = ? WHERE name = ?`,
		string(decision), enabled, artifactName,
	)
	if err != nil {
		return fmt.Errorf("generator: update feedback: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("generator: rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("generator: artifact %q not found", artifactName)
	}

	if decision == FeedbackDeleted {
		// Best-effort: remove the file but do not fail if it is already gone.
		_, fileName := artifactNameFromStructName(artifactName)
		filePath := filepath.Join(g.outputDir, fileName)
		if err := os.Remove(filePath); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("generator: remove %s: %w", filePath, err)
		}
	}
	return nil
}

// artifactNameFromStructName derives the file name for an already-known struct
// name (used during ApplyFeedback when we only have the DB name).
func artifactNameFromStructName(structName string) (string, string) {
	return structName, camelToSnake(structName) + ".go"
}

// structToKebab converts AutoValidator_RepeatFail_abc to
// auto-validator-repeat-fail-abc for use as the validator's Name() return.
func structToKebab(s string) string {
	return strings.ReplaceAll(strings.ToLower(s), "_", "-")
}
