import { Header } from "@/components/header";
import { getSkills } from "@/lib/cos-api";

export const dynamic = "force-dynamic";

export default async function SkillsPage() {
  const skills = await getSkills();

  return (
    <div>
      <Header
        title="Skills"
        description={`${skills.length} skills in catalog`}
      />
      <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {skills.map((skill) => (
          <div
            key={skill.name}
            className="rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-card)] p-5 hover:border-[var(--color-accent)] transition-colors"
          >
            <div className="flex items-start justify-between">
              <h3 className="font-semibold text-sm">{skill.name}</h3>
              {skill.autoGenerated && (
                <span className="rounded-full bg-[var(--color-warning)]/10 px-2 py-0.5 text-xs text-[var(--color-warning)]">
                  auto
                </span>
              )}
            </div>
            <p className="mt-2 text-xs text-[var(--color-text-muted)] line-clamp-2">
              {skill.description}
            </p>
            {skill.trigger && (
              <p className="mt-3 font-mono text-xs text-[var(--color-accent)]">
                /{skill.trigger}
              </p>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
