#!/usr/bin/env bash
# SCOPE: os-only
# settings-driver-opencode.sh — Project cognitive-os.yaml > harness.hooks
# into .opencode/cos-hooks.json for the OpenCode harness.
#
# ADR-064 Surface 2 Task 2.4: canonical hook registry lives in
# cognitive-os.yaml > harness.hooks. This driver is the single path that
# writes the OpenCode projection consumed by the cos-primitive-guard.js
# plugin (packages/opencode-adapter/plugins/cos-primitive-guard.js).
#
# OpenCode capability matrix (manifests/harness-driver-capabilities.yaml):
#   supported   : SessionStart, UserPromptSubmit, PreToolUse, PostToolUse, Stop
#   limited     : SubagentStart, PreCompact
#
# COS event → OpenCode native event mapping:
#   SessionStart      → session.created
#   UserPromptSubmit  → tui.prompt.append
#   PreToolUse        → tool.execute.before  (native-only: inline classifiers, no script projection)
#   PostToolUse       → tool.execute.after   (native-only: inline classifiers, no script projection)
#   Stop              → session.idle
#   PreCompact        → experimental.session.compacting (legacy: session.compacted)
#
# Latency policy:
#   - PreToolUse/PostToolUse hooks are NOT projected as scripts: the plugin
#     enforces tool-call governance natively (classifyBash/classifyRead/...).
#     Projecting 130+ per-tool-call bash spawns would freeze every tool call.
#   - Daemon launchers (hooks/*-launcher.sh) are forced async: true so the
#     plugin fire-and-forgets them instead of running them on the blocking
#     spawnSync path at session start.
#
# DO NOT EDIT .opencode/cos-hooks.json directly.
# This file is generated by: scripts/_lib/settings-driver-opencode.sh
# from: cognitive-os.yaml > harness.hooks
#
# Usage:
#   bash scripts/_lib/settings-driver-opencode.sh [--check]
#   source scripts/_lib/settings-driver-opencode.sh && opencode_driver_emit
#
# Flags:
#   --check          Dry-run: exit 0 if file is in sync, 1 if drift.
#   --harness=*      Accepted but ignored (this driver is opencode-only).
#
# Bash 3.x compatible.

set -euo pipefail

SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_SOURCE")" && pwd)"
COS_SOURCE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
if [ -z "${PYTHON_BIN:-}" ]; then
  if [ -x "$COS_SOURCE_DIR/.venv/bin/python" ]; then
    PYTHON_BIN="$COS_SOURCE_DIR/.venv/bin/python"
  else
    PYTHON_BIN="python3"
  fi
fi

# ── Resolve project root ───────────────────────────────────────────────────────
if [ -z "${PROJECT_DIR:-}" ]; then
  if [ -f "cognitive-os.yaml" ] || [ -d ".opencode" ]; then
    PROJECT_DIR="$(pwd)"
  else
    PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
  fi
fi

HOOKS_FILE="$PROJECT_DIR/.opencode/cos-hooks.json"
CONFIG_FILE="$PROJECT_DIR/opencode.json"
PLUGIN_SOURCE="$COS_SOURCE_DIR/packages/opencode-adapter/plugins/cos-primitive-guard.js"
PLUGIN_TARGET="$PROJECT_DIR/.opencode/plugins/cos-primitive-guard.js"

# ── Parse flags ───────────────────────────────────────────────────────────────
CHECK_MODE=false
for arg in "$@"; do
  case "$arg" in
    --check) CHECK_MODE=true ;;
    --harness=*) : ;;  # accepted but ignored (this driver is opencode-only)
    *) ;;
  esac
done

# ── Emit the full .opencode/cos-hooks.json content ────────────────────────────
# Strategy: delegate JSON synthesis to python3 + PyYAML so we read the same
# canonical hook registry that drives Codex / Bare-CLI, with no shell-side
# YAML parsing risk. See settings-driver-codex.sh for the parallel pattern.
opencode_driver_emit() {
  "$PYTHON_BIN" - "$PROJECT_DIR" <<'PYEOF'
import json
import sys
from pathlib import Path

import yaml

project_dir = Path(sys.argv[1])
config = yaml.safe_load((project_dir / "cognitive-os.yaml").read_text()) or {}
hooks = (config.get("harness") or {}).get("hooks") or {}

# OpenCode capability matrix (mirror manifests/harness-driver-capabilities.yaml):
# only events with status=supported in the opencode driver may project here.
COS_TO_OPENCODE_EVENT = {
    "SessionStart": "session.created",
    "UserPromptSubmit": "tui.prompt.append",
    "PreToolUse": "tool.execute.before",
    "PostToolUse": "tool.execute.after",
    "Stop": "session.idle",
    "PreCompact": "experimental.session.compacting",
}

# Canonical OpenCode event order (stable output for diffs).
OPENCODE_EVENT_ORDER = [
    "session.created",
    "tui.prompt.append",
    "tool.execute.before",
    "tool.execute.after",
    "session.idle",
    "experimental.session.compacting",
]

# Tool-call events are enforced natively by cos-primitive-guard.js inline
# classifiers. Projecting their scripts would add 130+ serial bash spawns to
# every single tool invocation, so the keys stay present but empty.
SCRIPT_PROJECTION_EXCLUDED_EVENTS = {"tool.execute.before", "tool.execute.after"}


def forced_async(script: str) -> bool:
    """Daemon launchers must never run on the plugin's blocking spawnSync path."""
    return Path(script).name.endswith("-launcher.sh")


def hook_entry(name: str, entry: dict) -> dict:
    """Render one hook into the cos-hooks.json shape.

    The cos-primitive-guard.js plugin expects:
      - script: path relative to project root (e.g., "hooks/session-init.sh")
      - id: unique identifier for the primitive (used in primitive-interventions)
      - event: the COS lifecycle event name (e.g., "SessionStart")
      - matcher: tool pattern filter (e.g., "Bash", "Edit|Write", empty for all)
      - async: boolean hint for fire-and-forget vs blocking
      - scope: scope tag preserved for debugging / kill-switch logic
    """
    script = str(entry.get("script") or "")
    return {
        "id": str(name),
        "script": script,
        "event": str(entry.get("event") or ""),
        "matcher": str(entry.get("matcher") or ""),
        "async": bool(entry.get("async", False)) or forced_async(script),
        "scope": str(entry.get("scope") or ""),
    }


by_event: dict[str, list[dict]] = {ev: [] for ev in OPENCODE_EVENT_ORDER}
for name, entry in hooks.items():
    if not isinstance(entry, dict):
        continue
    cos_event = entry.get("event")
    opencode_event = COS_TO_OPENCODE_EVENT.get(str(cos_event) or "")
    if not opencode_event:
        # Event is unsupported by OpenCode (SubagentStart, TeammateIdle,
        # TaskCreated, TaskCompleted, etc.). Drop silently — parity policy
        # treats these as advisory, not required.
        continue
    if opencode_event in SCRIPT_PROJECTION_EXCLUDED_EVENTS:
        continue
    if not entry.get("script"):
        continue
    by_event[opencode_event].append(hook_entry(str(name), entry))

# Also handle legacy PreCompact -> session.compacted fallback
# (the plugin reads both experimental.session.compacting and session.compacted)
if "PreCompact" in COS_TO_OPENCODE_EVENT:
    legacy_event = "session.compacted"
    if legacy_event not in by_event:
        by_event[legacy_event] = []

output = {
    "schema_version": 1,
    "harness": "opencode",
    "generated_by": "scripts/_lib/settings-driver-opencode.sh",
    "source": "cognitive-os.yaml > harness.hooks",
    "events": {ev: by_event.get(ev, []) for ev in OPENCODE_EVENT_ORDER},
}
# Also include legacy session.compacted for backward compatibility
if "PreCompact" in COS_TO_OPENCODE_EVENT:
    output["events"]["session.compacted"] = by_event.get("experimental.session.compacting", [])

print(json.dumps(output, indent=2, sort_keys=False))
PYEOF
}

# ── Emit the native opencode.json project config ──────────────────────────────
# Static shape: enables the COS plugin, instruction files, and points
# experimental.cognitive_os_hooks at the hook projection.
opencode_config_emit() {
  "$PYTHON_BIN" - <<'PYEOF'
import json

config = {
    "$schema": "https://opencode.ai/config.json",
    "instructions": [
        "AGENTS.md",
        ".cognitive-os/rules/cos/RULES-COMPACT.md",
        ".cognitive-os/rules/cos/*.md",
        ".cognitive-os/skills/cos/*/SKILL.md",
    ],
    "plugin": [".opencode/plugins/cos-primitive-guard.js"],
    "mcp": {},
    "permission": {"bash": "ask", "edit": "ask"},
    "experimental": {
        "cognitive_os_hooks": ".opencode/cos-hooks.json",
    },
}
print(json.dumps(config, indent=2, sort_keys=True))
PYEOF
}

# ── Main entrypoint (when invoked directly, not sourced) ──────────────────────
if [ "$SCRIPT_SOURCE" = "$0" ]; then
  if [ "$CHECK_MODE" = "true" ]; then
    if [ ! -f "$HOOKS_FILE" ] || [ ! -f "$CONFIG_FILE" ]; then
      echo "DRIFT: OpenCode projection missing ($HOOKS_FILE or $CONFIG_FILE)." >&2
      exit 1
    fi
    TMP_GENERATED="$(mktemp)"
    TMP_CONFIG="$(mktemp)"
    trap 'rm -f "$TMP_GENERATED" "$TMP_CONFIG"' EXIT
    opencode_driver_emit > "$TMP_GENERATED"
    opencode_config_emit > "$TMP_CONFIG"
    if [ -x "$PYTHON_BIN" ]; then
      "$PYTHON_BIN" -c "
import json, sys
pairs = [('$TMP_GENERATED', '$HOOKS_FILE'), ('$TMP_CONFIG', '$CONFIG_FILE')]
for expected, actual in pairs:
    with open(expected) as f: a = json.dumps(json.load(f), sort_keys=True, indent=2)
    with open(actual) as f: b = json.dumps(json.load(f), sort_keys=True, indent=2)
    if a != b:
        print(f'DRIFT detected between generated output and {actual}', file=sys.stderr)
        sys.exit(1)
print('OK: $HOOKS_FILE and $CONFIG_FILE are in sync with canonical harness.hooks')
"
    else
      if ! diff -q "$TMP_GENERATED" "$HOOKS_FILE" >/dev/null 2>&1 || ! diff -q "$TMP_CONFIG" "$CONFIG_FILE" >/dev/null 2>&1; then
        echo "DRIFT: $HOOKS_FILE or $CONFIG_FILE differs from generated output." >&2
        exit 1
      fi
      echo "OK: OpenCode projection is in sync (byte-level check, python unavailable)"
    fi
    exit 0
  fi

  # Normal mode: write .opencode/cos-hooks.json + opencode.json (atomic) and
  # install the project-local plugin copy.
  # Place the temp file on the SAME filesystem as the destination to keep
  # the rename atomic — same rationale as settings-driver-claude-code.sh.
  HOOKS_DIR="$(dirname "$HOOKS_FILE")"
  mkdir -p "$HOOKS_DIR" "$(dirname "$PLUGIN_TARGET")"
  if [ -f "$HOOKS_FILE" ]; then
    cp "$HOOKS_FILE" "$HOOKS_FILE.bak"
  fi
  TMP_OUT="$(mktemp "$HOOKS_DIR/.cos-hooks.json.XXXXXX")"
  TMP_CFG="$(mktemp "$PROJECT_DIR/.opencode.json.XXXXXX")"
  trap 'rm -f "$TMP_OUT" "$TMP_CFG"' EXIT
  opencode_driver_emit > "$TMP_OUT"
  opencode_config_emit > "$TMP_CFG"
  mv "$TMP_OUT" "$HOOKS_FILE"
  mv "$TMP_CFG" "$CONFIG_FILE"
  if [ -f "$PLUGIN_SOURCE" ]; then
    cp "$PLUGIN_SOURCE" "$PLUGIN_TARGET"
  fi
  hook_count=$(grep -c '"script":' "$HOOKS_FILE" || true)
  echo "settings-driver-opencode: wrote $CONFIG_FILE and $HOOKS_FILE ($hook_count hook entries)"
fi