#!/usr/bin/env bash
# SCOPE: os-only
# settings-driver-codex.sh — Project cognitive-os.yaml > harness.hooks
# into .codex/hooks.json for the Codex harness.
#
# ADR-064: canonical hook registry lives in cognitive-os.yaml > harness.hooks.
# This driver is the single path that writes .codex/hooks.json.
#
# Codex hook contract — the authority is manifests/codex-hooks-schema.yaml
# (transcribed from learn.chatgpt.com/docs and openai/codex docs/config.md,
# verified 2026-08-15).  Do not restate the contract here; restated contracts
# drift.  What this driver does with it:
#   - Output is wrapped in the MANDATORY top-level "hooks" namespace. Without
#     it Codex does not parse the file at all and every hook is inert.
#   - Matchers are regexes over the TOOL NAME for PreToolUse/PostToolUse:
#     "^Bash$", "^apply_patch$".  There is no "bash" matcher.
#   - UserPromptSubmit and Stop do NOT accept a matcher: their groups are
#     emitted with no "matcher" key.  The old "prompt"/"shutdown" matchers were
#     invented and matched nothing.
#   - Edit / Write / MultiEdit have no Codex equivalent; they are mapped onto
#     apply_patch, Codex's only file-mutation tool.  Without that mapping the
#     write-side guard coverage on Codex is exactly zero.
#   - "async" is parsed by Codex but not honoured, so it is never emitted.
#   - SessionStart keeps matcher "startup" (resume/clear/compact are an open
#     gap, recorded in the manifest under known_projection_gaps).
#   - NOT projected: SubagentStart/SubagentStop, PreCompact/PostCompact,
#     PermissionRequest.  TeammateIdle/TaskCreated/TaskCompleted are COS
#     extension events and require cos-runner.
#   - TRUST GATE: non-managed command hooks do not run until the operator
#     trusts the .codex/ layer with /hooks.  Writing this file is not enabling
#     it.
#
# DO NOT EDIT .codex/hooks.json directly.
# This file is generated by: scripts/_lib/settings-driver-codex.sh
# from: cognitive-os.yaml > harness.hooks
#
# Usage:
#   bash scripts/_lib/settings-driver-codex.sh [--check]
#   source scripts/_lib/settings-driver-codex.sh && codex_driver_emit
#
# Flags:
#   --check   Dry-run: exit 0 if .codex/hooks.json is in sync, 1 if drift.
#
# Bash 3.x compatible.

set -euo pipefail

SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_SOURCE")" && pwd)"

# ── Resolve project root ───────────────────────────────────────────────────────
if [ -z "${PROJECT_DIR:-}" ]; then
  if [ -f "cognitive-os.yaml" ] || [ -d ".codex" ]; then
    PROJECT_DIR="$(pwd)"
  else
    PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
  fi
fi

HOOKS_FILE="$PROJECT_DIR/.codex/hooks.json"
PROFILE="${PROFILE:-default}"
case "$PROFILE" in
  default) PROFILE="maintainer" ;;
  core|maintainer|full) ;;
  *) PROFILE="maintainer" ;;
esac
export PROFILE

# ── Parse flags ───────────────────────────────────────────────────────────────
CHECK_MODE=false
for arg in "$@"; do
  case "$arg" in
    --check) CHECK_MODE=true ;;
    --harness=*) : ;;  # accepted but ignored (this driver is Codex-only)
    *) ;;
  esac
done

# ── Build a single Codex hook command entry ───────────────────────────────────
_codex_entry() {
  local script="$1"
  # Codex command: set env then conditionally run the script (guard against
  # missing script during first-install when hooks.json is written before
  # self-install.sh has run).  Do not append `|| true`: an existing hook's
  # exit code is the hook decision, and exit 2 must remain able to block.
  # NOTE: the JSON "command" string must use escaped double quotes for $PWD paths,
  # matching the format in the original hand-maintained .codex/hooks.json.
  # ADR: hook-lib-projection-contract — source the shared PYTHONPATH bootstrap
  # before running the hook so Codex hooks that `import cos_lib.<mod>` resolve
  # against the projected .cognitive-os/lib/ package, same as the Claude
  # timing-wrapper path. Best-effort (`|| true`): missing bootstrap file
  # during first-install must not block the hook from running.
  printf '        {\n          "type": "command",\n          "command": "export COGNITIVE_OS_HARNESS=codex; export COGNITIVE_OS_PROJECT_DIR=\\"${COGNITIVE_OS_PROJECT_DIR:-${CODEX_PROJECT_DIR:-$PWD}}\\"; source \\"$PWD/.cognitive-os/hooks/cos/_lib/hook-python-env.sh\\" 2>/dev/null || true; if [ -x \\"$PWD/%s\\" ]; then bash \\"$PWD/%s\\"; fi"\n        }' \
    "$script" "$script"
}

# ── Build a group of Codex hook entries for one event key ────────────────────
# Usage: _codex_group <codex_matcher> <script1> <script2> ...
_codex_group() {
  local matcher="$1"
  shift
  local entries=""
  local first=true
  for script in "$@"; do
    if [ "$first" = true ]; then
      first=false
    else
      entries="$entries,"$'\n'
    fi
    entries="$entries$(_codex_entry "$script")"
  done

  cat <<GROUPEOF
    {
      "hooks": [
$entries
      ],
      "matcher": "$matcher"
    }
GROUPEOF
}

# ── Emit the full .codex/hooks.json content ───────────────────────────────────
codex_driver_emit() {
  python3 - "$PROJECT_DIR" "$PROFILE" <<'PYEOF'
import json
import sys
from pathlib import Path

import yaml

project_dir = Path(sys.argv[1])
profile = sys.argv[2]
config = yaml.safe_load((project_dir / "cognitive-os.yaml").read_text()) or {}
hooks = (config.get("harness") or {}).get("hooks") or {}

# Authority: manifests/codex-hooks-schema.yaml. Events that do not accept a
# matcher map to None (no "matcher" key emitted); tool events map to a regex
# over the tool name.
EVENT_ORDER = ["SessionStart", "UserPromptSubmit", "PreToolUse", "PostToolUse", "Stop"]
# SessionStart: enum matcher. resume/clear/compact are an open gap (manifest).
EVENT_MATCHERS = {"SessionStart": "startup"}
# Events whose groups carry NO matcher key at all.
MATCHERLESS_EVENTS = {"UserPromptSubmit", "Stop"}
TOOL_EVENTS = {"PreToolUse", "PostToolUse"}

# Claude Code tool names → Codex tool-name regex. Codex mutates files through
# the single apply_patch tool, so every Edit/Write/MultiEdit guard lands there.
BASH_MATCHER = "^Bash$"
APPLY_PATCH_MATCHER = "^apply_patch$"
TOOL_NAME_TRANSLATION = {
    "Bash": BASH_MATCHER,
    "Edit": APPLY_PATCH_MATCHER,
    "Write": APPLY_PATCH_MATCHER,
    "MultiEdit": APPLY_PATCH_MATCHER,
}

_SENTINEL = object()


def codex_matcher(entry):
    """Return the Codex matcher, None for matcherless events, or _SENTINEL to skip."""
    event = entry.get("event")
    if event in MATCHERLESS_EVENTS:
        return None
    if event in EVENT_MATCHERS:
        return EVENT_MATCHERS[event]
    if event in TOOL_EVENTS:
        # A COS matcher is a "|"-joined set of Claude Code tool names. Translate
        # each name; a hook registered for Bash|Edit|Write becomes two Codex
        # groups (^Bash$ and ^apply_patch$) so neither surface loses the guard.
        raw = str(entry.get("matcher") or "")
        translated = []
        for name in raw.split("|"):
            mapped = TOOL_NAME_TRANSLATION.get(name.strip())
            if mapped and mapped not in translated:
                translated.append(mapped)
        return translated or _SENTINEL
    return _SENTINEL


def command_for(script: str) -> dict:
    return {
        "type": "command",
        "command": (
            'export COGNITIVE_OS_HARNESS=codex; '
            'export COGNITIVE_OS_PROJECT_DIR="${COGNITIVE_OS_PROJECT_DIR:-${CODEX_PROJECT_DIR:-$PWD}}"; '
            # Missing scripts are harmless during first install. Existing hook
            # scripts must keep their exit code so Codex Bash gates can block.
            f'if [ -x "$PWD/{script}" ]; then bash "$PWD/{script}"; fi'
        ),
    }


def groups_for(event):
    by_matcher = {}
    for entry in hooks.values():
        if not isinstance(entry, dict) or entry.get("event") != event:
            continue
        matcher = codex_matcher(entry)
        if matcher is _SENTINEL:
            continue
        script = entry.get("script")
        if not script:
            continue
        matchers = matcher if isinstance(matcher, list) else [matcher]
        for one in matchers:
            # ADR-311 interactive profile: Codex has the same Bash hot-path
            # budget problem as Claude Code. In core/default/maintainer,
            # represent the Bash governance mesh through
            # bash-hot-path-dispatcher.sh; PROFILE=full remains the exhaustive
            # SO/release projection. Scoped to Bash only — apply_patch guards
            # are not part of the Bash hot path and must never be thinned.
            if event == "PreToolUse" and one == BASH_MATCHER:
                is_dispatcher = str(script) == "hooks/bash-hot-path-dispatcher.sh"
                if profile != "full" and not is_dispatcher:
                    continue
                if profile == "full" and is_dispatcher:
                    continue
            by_matcher.setdefault(one, []).append(command_for(str(script)))

    groups = []
    for matcher, entries in by_matcher.items():
        group = {"hooks": entries}
        # Events that do not accept a matcher must not carry the key at all.
        if matcher is not None:
            group["matcher"] = matcher
        groups.append(group)
    return groups


# The top-level "hooks" namespace is mandatory: without it Codex does not read
# the file as a hook registry and every projected guard is silently inert.
output = {"hooks": {event: groups_for(event) for event in EVENT_ORDER}}
print(json.dumps(output, indent=2))
PYEOF
}

# ── Main entrypoint (when invoked directly, not sourced) ──────────────────────
if [ "$SCRIPT_SOURCE" = "$0" ]; then
  if [ "$CHECK_MODE" = "true" ]; then
    if [ ! -f "$HOOKS_FILE" ]; then
      echo "DRIFT: $HOOKS_FILE does not exist." >&2
      exit 1
    fi
    TMP_GENERATED="$(mktemp)"
    trap 'rm -f "$TMP_GENERATED"' EXIT
    codex_driver_emit > "$TMP_GENERATED"
    if command -v python3 >/dev/null 2>&1; then
      python3 -c "
import json, sys
with open('$TMP_GENERATED') as f: a = json.dumps(json.load(f), sort_keys=True, indent=2)
with open('$HOOKS_FILE') as f: b = json.dumps(json.load(f), sort_keys=True, indent=2)
if a != b:
    print('DRIFT detected between generated output and $HOOKS_FILE', file=sys.stderr)
    sys.exit(1)
else:
    print('OK: $HOOKS_FILE is in sync with canonical harness.hooks')
"
    else
      if ! diff -q "$TMP_GENERATED" "$HOOKS_FILE" >/dev/null 2>&1; then
        echo "DRIFT: $HOOKS_FILE differs from generated output." >&2
        exit 1
      fi
      echo "OK: $HOOKS_FILE is in sync (byte-level check, python3 not available)"
    fi
    exit 0
  fi

  # Normal mode: write .codex/hooks.json (atomic)
  mkdir -p "$(dirname "$HOOKS_FILE")"
  if [ -f "$HOOKS_FILE" ]; then
    cp "$HOOKS_FILE" "$HOOKS_FILE.bak"
  fi
  TMP_OUT="$(mktemp)"
  trap 'rm -f "$TMP_OUT"' EXIT
  codex_driver_emit > "$TMP_OUT"
  mv "$TMP_OUT" "$HOOKS_FILE"
  hook_count=$(grep -c '"command":' "$HOOKS_FILE" || true)
  echo "settings-driver-codex: wrote $HOOKS_FILE ($hook_count hook commands)"
  # Trust gate (manifests/codex-hooks-schema.yaml > trust): Codex does not run
  # non-managed command hooks until the operator trusts the layer. Writing the
  # file is not enabling it.
  echo "settings-driver-codex: NOT active yet — Codex requires trust for non-managed"
  echo "settings-driver-codex: command hooks. Run /hooks in Codex and trust .codex/,"
  echo "settings-driver-codex: otherwise every projected guard stays inert."
fi
