"""Behavioral tests for skills/session-backlog — ADR-059 Phase 1 pilot.

session-backlog scans multiple sources and writes a structured backlog document.
Tests validate the output format, priority tier model, and the lib/request_queue
module that the skill references (no LLM calls needed).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_LIB_DIR = str(PROJECT_ROOT / "lib")
if _LIB_DIR not in sys.path:
    sys.path.insert(0, _LIB_DIR)

pytestmark = pytest.mark.unit

PRIORITY_TIERS = [
    "Priority 1",
    "Priority 2",
    "Priority 3",
    "Priority 4",
]

BACKLOG_REQUIRED_SECTIONS = [
    "# Session Backlog",
    "## Priority 1",
    "## Priority 2",
    "## Priority 3",
    "## Priority 4",
    "## Plans Status Summary",
    "## Recommendations for Next Session",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def build_sample_backlog(
    p1_items: list[str] | None = None,
    date: str = "2026-04-24",
) -> str:
    p1_rows = ""
    if p1_items:
        for item in p1_items:
            p1_rows += f"| {item} | plan | continue work | 1 session |\n"
    if not p1_rows:
        p1_rows = "_(none found)_"

    return f"""# Session Backlog — {date}

> Generated by /session-backlog. Sources scanned: plans, engram, active-tasks, dispatch-queue, session TODOs, audit results, git state.

## Priority 1: In-Progress (resume immediately)

| Task | Source | Context | Est. Effort |
|------|--------|---------|-------------|
{p1_rows}

## Priority 2: Ready to Start (dependencies met)

| Task | Source | Blocked by | Est. Effort |
|------|--------|-----------|-------------|
_(none found)_

## Priority 3: Planned (needs prerequisites)

| Task | Source | Prerequisites | Est. Effort |
|------|--------|--------------|-------------|
_(none found)_

## Priority 4: Backlog (no urgency)

| Task | Source | Notes | Est. Effort |
|------|--------|-------|-------------|
_(none found)_

## Plans Status Summary

| Plan | Progress | Next Phase | Est. Remaining |
|------|----------|------------|----------------|

## Recommendations for Next Session

1. **Start with**: implement ADR-059 pilot tests
2. **Quick wins**: run pytest, update CATALOG
3. **Can parallelize**: documentation update, config validation

---
_Backlog generated: 2026-04-24T10:00:00Z | Items: 1 | Sources: plans_
"""


# ---------------------------------------------------------------------------
# 1. Imports / invocation — SKILL.md and request_queue module exist
# ---------------------------------------------------------------------------


class TestSessionBacklogSkillExists:
    def test_skill_md_present(self):
        skill_md = PROJECT_ROOT / "skills" / "session-backlog" / "SKILL.md"
        assert skill_md.exists()

    def test_request_queue_module_exists(self):
        """SKILL.md Step 7b references lib/request_queue — it must exist."""
        rq = PROJECT_ROOT / "lib" / "request_queue.py"
        assert rq.exists(), f"Missing lib/request_queue.py — backlog Step 7b broken"

    def test_request_queue_importable(self):
        """request_queue must import without errors."""
        try:
            import request_queue  # noqa: F401
        except ImportError as e:
            pytest.fail(f"request_queue.py is not importable: {e}")


# ---------------------------------------------------------------------------
# 2. Contract test — backlog output format compliance
# ---------------------------------------------------------------------------


class TestSessionBacklogContract:
    def test_all_required_sections_present(self):
        """A well-formed backlog must contain all 7 required sections."""
        backlog = build_sample_backlog()
        for section in BACKLOG_REQUIRED_SECTIONS:
            assert section in backlog, f"Missing required section: {section!r}"

    def test_generation_metadata_present(self):
        """Backlog footer must contain generation timestamp, item count, and sources."""
        backlog = build_sample_backlog()
        assert "Backlog generated:" in backlog
        assert "Items:" in backlog
        assert "Sources:" in backlog

    def test_date_appears_in_header(self):
        """Backlog header must show the generation date."""
        date = "2026-04-24"
        backlog = build_sample_backlog(date=date)
        assert date in backlog

    def test_priority_tiers_in_order(self):
        """Priority tiers must appear in order: 1, 2, 3, 4."""
        backlog = build_sample_backlog()
        positions = [backlog.find(f"## Priority {i}") for i in range(1, 5)]
        assert all(p >= 0 for p in positions), "Not all priority tiers found"
        assert positions == sorted(positions), "Priority tiers are out of order"


# ---------------------------------------------------------------------------
# 3. Happy path — effort estimate labels
# ---------------------------------------------------------------------------


class TestSessionBacklogHappyPath:
    def test_effort_estimates_use_defined_scale(self):
        """Effort estimates must use the 4-level scale from SKILL.md."""
        valid_efforts = {"< 30min", "1 session", "2-3 sessions", "> 3 sessions"}
        # Verify the SKILL.md documents these values
        skill_md = PROJECT_ROOT / "skills" / "session-backlog" / "SKILL.md"
        content = skill_md.read_text()
        for effort in valid_efforts:
            assert effort in content, (
                f"SKILL.md missing effort scale entry: {effort!r}"
            )

    def test_empty_priority_section_uses_none_found_marker(self):
        """When a priority section has no items, it must use '_(none found)_' marker."""
        backlog = build_sample_backlog(p1_items=None)
        # P1 should have the none found marker when no items
        assert "_(none found)_" in backlog

    def test_backlog_file_can_be_written_to_tmp_path(self, tmp_path: Path):
        """Writing the backlog to .cognitive-os/sessions/{id}/backlog.md must succeed."""
        session_id = "test-session-001"
        session_dir = tmp_path / ".cognitive-os" / "sessions" / session_id
        session_dir.mkdir(parents=True)

        backlog_file = session_dir / "backlog.md"
        content = build_sample_backlog()
        backlog_file.write_text(content)

        assert backlog_file.exists()
        read_back = backlog_file.read_text()
        assert "# Session Backlog" in read_back

    def test_request_queue_get_pending_requests_callable(self, tmp_path: Path):
        """request_queue.get_pending_requests() must be callable on an empty session dir."""
        import request_queue

        session_dir = tmp_path / ".cognitive-os" / "sessions" / "test-s1"
        session_dir.mkdir(parents=True)

        # Create empty user-requests.jsonl
        (session_dir / "user-requests.jsonl").write_text("")

        result = request_queue.get_pending_requests(session_dir=str(session_dir))
        assert isinstance(result, list), (
            "get_pending_requests() must return a list"
        )


# ---------------------------------------------------------------------------
# 4. Error handling — missing sources are handled gracefully
# ---------------------------------------------------------------------------


class TestSessionBacklogErrorHandling:
    def test_skill_documents_engram_unavailable_fallback(self):
        """SKILL.md must document behavior when Engram is unavailable."""
        skill_md = PROJECT_ROOT / "skills" / "session-backlog" / "SKILL.md"
        content = skill_md.read_text()
        assert "Engram unavailable" in content or "engram" in content.lower()

    def test_skill_documents_missing_plans_dir_fallback(self):
        """SKILL.md must document behavior when .cognitive-os/plans/ is absent."""
        skill_md = PROJECT_ROOT / "skills" / "session-backlog" / "SKILL.md"
        content = skill_md.read_text()
        assert "plans/" in content and ("absent" in content or "does not exist" in content
                                         or "not exist" in content)

    def test_user_requests_jsonl_malformed_line_raises(self, tmp_path: Path):
        """Malformed JSONL in user-requests.jsonl must raise JSONDecodeError."""
        bad_file = tmp_path / "user-requests.jsonl"
        bad_file.write_text('{"status": "pending", "unclosed\n')

        with pytest.raises(json.JSONDecodeError):
            for line in bad_file.read_text().strip().splitlines():
                if line.strip():
                    json.loads(line)
